name: pre-commit
on:
  push:

    branches:
      - 'fix/*'
      - 'fixes/*'
      - 'feature/*'
      - 'features/*'
      - 'hotfix/*'
      - 'hotfixes/*'
      - 'release/*'
      - 'releases/*'
      - 'chore/*'
      - 'chores/*'
      - 'automatic*'

permissions: read-all

jobs:
  pre-commit:
    permissions:
      contents: write
    uses: boldlink/terraform-module-support/.github/workflows/pre-commit.yaml@main
    secrets:
      AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
      SLACK_WEBHOOK : ${{secrets.SLACK_WEBHOOK}}
